# Generated by Django 3.1.3 on 2020-12-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travelling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impfle',
            name='im',
            field=models.ImageField(default='blank-profile-picture.png', null=True, upload_to='Profile/'),
        ),
    ]
