# Generated by Django 3.1.3 on 2020-12-31 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travelling', '0003_auto_20201231_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='DOB',
        ),
    ]
