# Generated by Django 3.1.3 on 2020-12-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travelling', '0005_city_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='city',
            name='date',
        ),
    ]
