# Generated by Django 3.1.3 on 2021-01-01 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travelling', '0006_auto_20201231_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date',
            old_name='date',
            new_name='da',
        ),
    ]
