# Generated by Django 3.1.3 on 2021-01-01 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Travelling', '0007_auto_20210101_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='e',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
