# Generated by Django 3.1.3 on 2021-01-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travelling', '0008_city_e'),
    ]

    operations = [
        migrations.DeleteModel(
            name='date',
        ),
        migrations.AddField(
            model_name='city',
            name='da',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='places',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
